apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DATABASE_URL: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/mydatabase
